### PR TITLE
Bump build number to trigger rebuild

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is just a rebuild. The currently ongoing libgdal migration (3.5 -> 3.6) triggered a rebuild of gazebo, which fails to solve because the present libraw build is too old.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
@conda-forge/libraw, ready for review. Please have a look :)

**Comment by hmaarrfk** [comment]
Did you need this for the lcms2 "migration"?

If so, I might have done that in https://github.com/conda-forge/libraw-feedstock/pull/10/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aL38

it was unclear what we were getting from "here" but I think I achieved the same thing.

**Comment by zklaus** [comment]
It was literally just a rebuild with no changes to bring it to the new toolchain. Without it, it was a blocker (not-solvable) for a package in the libgdal migration, but your PR did indeed resolve this issue as well.

Thanks!

**Comment by hmaarrfk** [comment]
FYI: I think it was the stricter pinning on lcms2 then. The toolchains upgrade was designed to be very widely compatible.

**Pull request closed without merging**
